### ISSUE TITLE
Batch program error

### ISSUE THREAD

**Issue by Yoposoc** [dnsev/4cs#2]
I get a "System cannot find path specified." Error when I try using the batch program to re-encode old files.

**Comment by dnsev** [comment]
Note that this is assuming you put "embed.exe" inside the same folder as "batch-re-encode.exe".

Also found another bug with an issue with spaces in the path, so that's also fixed too.

**Comment by Yoposoc** [comment]
So I have these in the same folder:
embed.exe
batch-re-encode.exe
extract.exe
I drag an embedded picture that doesn't work anymore and drag it to batch-re-encode.exe. The cmd windows pops up for a second. I can't see if there's an error.
I just tried to post it. It doesn't work. Am I being an idiot? Or should I send one of the image files to you for you to test?

**Comment by dnsev** [comment]
Oh I think I see what you mean. There was an issue with the format you were probably trying to use.
The cmd window popping up is desired behavior.

It should be fixed now; if you get any more issues with it, say so.

Similarly, I fixed an odd issue with .png playback in the web player.

**Comment by Yoposoc** [comment]
I still get "Image contains embedded archive."
;_;
Is my 352 image file collection for sound threads worthless?

**Comment by dnsev** [comment]
I've had a false positive "Image contains embedded archive." once before using the stega-png format when I know there was no conceivable way that they could have fixed it that quickly (this was a few days after release) nor should they have been able to fix it.

In so far as I've seen, it hasn't been "fixed," and so long as you're using the correctly outputted files (the ones that will end in "-embed.png") they should be postable. If one doesn't work, it might be a false positive; try another. If all of them don't work, that's bizarre.

I tried the process just now and it worked without flaw.

If somehow you're messing up how the process should work, check [this image](https://f.cloud.github.com/assets/3087287/72171/6592889e-6006-11e2-9025-27b938dd0f95.png).

And if the problem persists, see if you can reply and upload an image the issue in the comment, both the original image and the embedded one.

**Comment by Yoposoc** [comment]
Ah, I thought it was weird that the cmd window closes immediately. I've only been testing .gif files, which don't work. I just tried a .png as well as a .jpg and it seems to be working fine.

Is .gif support a work in progress?

**Comment by dnsev** [comment]
Gif isn't currently supported for re-encoding. You can use the decoder to extract the image, but re-encoding isn't supported as it loses a lot of picture information in the process, since .png's aren't animated.

I may sometime make it use the first frame of the .gif and encode that as the image, but it's not currently at that point.

Update:
Added .gif support.

**Comment by Yoposoc** [comment]
Thanks a lot! You are super awesome.
